FORMAT: 1A
HOST: http://83.144.64.150:9001/

# noodle
Notes API is a

# Session
Notes related resources of the Every change will be comitted, but it disable aout commit, still nice

## Check [/auth/checkSession]
### List all Notes [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "title": "Jogging in park"
        }, {
          "id": 2, "title": "Pick-up posters from post-office"
        }]